Finish Assignment
webprogramminghack/assignment-class18 pull request #1
Opened 2024-10-06 14:20 UTC by supriadiacep

2024-10-07 15:42 UTC, webprogramminghack requested changes

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Button/Button.module.scss
> +  padding: 13px 20px;
Gunakan rem-calc untuk semua kecuali untuk value 1px

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    margin: 32px 39px 41px;
Gunakan rem-calc untuk semua kecuali border 1px

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +export type DialogProps = {
Kalau variantnya success, isDisabled prop tidak boleh tersedia. Pahami kode ini dan gunakan:
```
type DialogVariant = 'success' | 'info' | 'danger';

type DialogProps<V extends DialogVariant = DialogVariant> = {
  title: string;
  description: string;
  variant: V;
  confirmValue?: string;
  isDisabled?: V extends 'success' ? never : boolean;
  onConfirm?: () => void;
  onClose?: () => void;
};
```

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +      // const _exhaustiveCheck: never = variant;
Error ini bisa diselesaikan dengan memasukkan kode tersebut ke dalam sebuah scope. Lakukan ini:
```
const getSrcVariant = (variant: DialogProps['variant']): React.ReactElement => {
  switch (variant) {
    case 'success':
      return <ImageSuccess className={clsx(styles.icon)} />;
    case 'info':
      return <ImageInfo className={clsx(styles.icon)} />;
    case 'danger':
      return <ImageDanger className={clsx(styles.icon)} />;
    default: {
      const _exhaustiveCheck: never = variant;
      throw new Error(`Unhandled variant: ${_exhaustiveCheck}`);
    }
  }
};
```

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +  ...props
Tidak perlu menggunakan rest parameter, pada kode ini kita tidak membutuhkan itu.

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +export const Dialog: FC<DialogProps> = ({
Gunakan Generic Functional Component untuk infer variant sehingga kita bisa mengatur apakah prop isDisabled harus available atau tidak. Pahami dan gunakan kode berikut:
```
export const Dialog = <V extends DialogVariant>({
  title,
  description,
  variant,
  confirmValue = 'Confirm',
  isDisabled,
  onConfirm,
  onClose,
}: DialogProps<V>) => {
```

Jangan menggunakan React.FC<DialogVariant>, React.FC tidak suitable untuk generic functional component (silahkan dicoba, prop isDisablednya tidak akan memunculkan error jika kita pakai walaupun variantnya adalah 'success')

2024-10-07 15:42 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +          {variant === 'success' && (
Hati-hati, pada design variant 'success' hanya memiliki secondary button

2024-10-07 15:44 UTC, webprogramminghack commented
Ganti import font pada file `_fontFamily.scss` menjadi:
```
@import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap');
```

Saya lupa provide font nya. Pada design kita membutuhkan font red hat display.

2024-10-07 15:51 UTC, webprogramminghack requested changes

2024-10-07 15:51 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    position: absolute;
Menurut saya, css nya masih tergolong kotor. Kenapa harus menggunakan position absolute?

2024-10-07 15:51 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +      justify-content: flex-start;
flex-start adalah nilai default, hilangkan saja.

2024-10-07 15:51 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +  border-radius: 5px 5px;
Sederhanakan menjadi border-radius: rem-calc(5);

2024-10-07 15:55 UTC, webprogramminghack requested changes

2024-10-07 15:55 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +  isDisabled = false,
Tidak usah memakai default value, kalau tidak di provide valuenya akan `undefined`. Coba lihat tipe data argument disabled pada gambar:
![CleanShot 2024-10-07 at 22 53 25@2x](https://github.com/user-attachments/assets/2fc51640-a342-4f9b-b0c2-f156f8e24126)

Tertera `boolean | undefined`.

Jadi tidak usah memberikan default value `false`.

2024-10-09 19:46 UTC, webprogramminghack requested changes

2024-10-09 19:46 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +          {variant === 'success' && (
Ini belum diselesaikan, tolong perbaiki:
![CleanShot 2024-10-10 at 02 44 52@2x](https://github.com/user-attachments/assets/1b8e3771-dce3-441c-9ea6-d639907b73b1)

2024-10-09 19:48 UTC, webprogramminghack requested changes

2024-10-09 19:48 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +  width: 37.5rem;
Gunakan rem-calc

2024-10-09 19:54 UTC, webprogramminghack requested changes

2024-10-09 19:54 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    border-radius: 0px 0px rem-calc(5) rem-calc(5);
0px tidak perlu tulis px. Tulis saja 0.

2024-10-09 20:44 UTC, hafidzlvm commented
oke, noted koh

2024-10-09 21:12 UTC, webprogramminghack commented
Well done!!!
![CleanShot 2024-10-10 at 04 09 13@2x](https://github.com/user-attachments/assets/5c8aad21-6b10-4b41-8917-a92d06d82d2f)

2024-10-09 21:12 UTC, closed without merging