Finishing Assignment #18 React-Dialog-Box
webprogramminghack/assignment-class18 pull request #2
Opened 2024-10-08 09:21 UTC by pramudios

Mohon direview, beberapa codes terinspirasi dari courtesy kodingan pak Acep dan Chat Gpt...

2024-11-05 08:10 UTC, webprogramminghack requested changes
Fix the code according to the comments provided

2024-11-05 08:10 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +  width: 37.5rem;
Gunakan rem_calc

2024-11-05 08:10 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    align-items: center;
2 style berikut dapat dihapus saja, karena tidak memberikan styling apapun (secara default content sudah flex-start dan items center)

2024-11-05 08:10 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    bottom: 0;
2 style berikut dapat dihapus saja, karena tidak memberikan styling apapun

2024-11-05 08:10 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    border-radius: 0px 0px 5px 5px;
Lebih baik gunakan rem_calc

2024-11-05 08:10 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +      align-items: flex-start;
2 style berikut dapat dihapus saja, karena tidak memberikan styling apapun (secara default sudah flex-start)

2024-11-05 08:10 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +      margin-right: rem_calc(16);
Lebih baik dihapus saja, karena tidak memberikan style apapun, dan tidak perlu untuk margin-right, karena margin sudah diatur oleh margin-left: rem_calc(24); pada .alertText

2024-11-05 08:10 UTC, webprogramminghack commented on src/App.tsx
> +          />
Tambahkan prop isDisabled pada Dialog, sehingga jika ingin disabled button tidak harus lewat dialogProps

2024-11-05 08:10 UTC, webprogramminghack commented on src/App.tsx
> +      </Button>
Tambahkan juga 2 button untuk show alert info dan danger, namun dengan button disabled lewat prop Dialog, bukan dialogProps

2024-11-14 06:36 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +  width: 37.5rem;
<img width="419" alt="image" src="https://github.com/user-attachments/assets/c8b4062a-028e-4e96-80c2-3b07dd77833c">

2024-11-14 08:49 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +  width: 37.5rem;
<img width="409" alt="image" src="https://github.com/user-attachments/assets/135dc5ee-d4e6-49b9-9491-fd17bac19278">
Sudah menggunakan rem_calc

2024-11-14 08:50 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +    align-items: center;
<img width="421" alt="image" src="https://github.com/user-attachments/assets/8cd5234e-c5a0-47df-af1c-2d60ada62f5b">

Sudah dihapus (saya komen untuk pembelajaran)

2024-11-14 08:54 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +    bottom: 0;
<img width="401" alt="image" src="https://github.com/user-attachments/assets/c98d8ea6-617b-40c3-8e2a-500b92a53f84">

udah dihapus (saya komen untuk pembelajaran)

2024-11-14 09:00 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +    border-radius: 0px 0px 5px 5px;
<img width="300" alt="image" src="https://github.com/user-attachments/assets/ca8f7a7b-99b9-4c94-a565-2d05467742f2">

Sudah menggunakan rem_calc

2024-11-14 09:01 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +      align-items: flex-start;
<img width="399" alt="image" src="https://github.com/user-attachments/assets/426d96c2-9561-439a-8eaa-da188100b6db">

Sudah dihapus (saya komen untuk pembelajaran)

2024-11-14 09:04 UTC, pramudios commented on src/components/Dialog/Dialog.module.scss
> +      margin-right: rem_calc(16);
<img width="396" alt="image" src="https://github.com/user-attachments/assets/79d8785f-7428-4c67-be39-bf622c020b72">

Sudah dihapus (saya komen untuk pembelajaran)

2024-11-14 09:09 UTC, pramudios commented on src/App.tsx
> +          />
<img width="404" alt="image" src="https://github.com/user-attachments/assets/137edd11-dbd9-410f-921e-a4eea9e66129">

Sudah ditambahkan prop isDisabled pada Dialog

2024-11-14 09:11 UTC, pramudios commented on src/App.tsx
> +      </Button>
<img width="416" alt="image" src="https://github.com/user-attachments/assets/23f6e995-5245-4243-bfa5-719853e73ec7">
<img width="354" alt="image" src="https://github.com/user-attachments/assets/c09b7f92-467c-41e9-b10c-6cda21ce74b6">

Sudah ditambahkan button disabled lewat prop Dialog, jika bernilai **true**, maka button akan disabled

2025-01-09 07:56 UTC, webprogramminghack approved these changes
Assignment completed, good job

2025-01-09 07:56 UTC, closed without merging