Wph 004 rudy
webprogramminghack/assignment-class18 pull request #3
Opened 2024-10-10 04:54 UTC by RudyHarun99

mohon koreksi dan sarannya, terima kasih

2024-10-10 11:29 UTC, webprogramminghack requested changes

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +  const [content, setContent] = useState({
Tidak perlu state, state adalah data storage yang digunakan untuk perubahan data yang akan mengakibatkan render. Jadikan ini sebagai prop.

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +  useEffect(() => {
Tidak perlu useEffect. useEffect adalah side effect yang kita set kalau komponennya di render. title dan description harusnya bagian dari props.

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +  border: 1px 0px 0px 0px;
Nilai 0 jangan ditulis menggunakan px. Cukup 0 saja. Jadi daripada 0px, kita tulis 0. Nilai 0px lainnya juga tolong diganti ke 0.

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +    <div className={clsx(styles.dialog)}>
Kalau classnya hanya 1, contohnya hanya `styles.dialog`, maka tidak perlu menggunakan clsx. clsx digunakan jika classnya lebih dari 1. Perbaiki yang lainnya juga.

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +  left: rem-calc(-942);
Tidak perlu menggunakan ini, dialognya akan ke tengah secara otomatis. Careful, usahakan clean code, jangan pakai value yang dikira-kira.

![CleanShot 2024-10-10 at 18 21 56@2x](https://github.com/user-attachments/assets/4a8497ce-5acc-4906-b4f4-5b03f308be5e)

![CleanShot 2024-10-10 at 18 23 05@2x](https://github.com/user-attachments/assets/9d4673c7-3040-43cc-a2b3-a2df93c9f831)

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.module.scss
> +    flex-direction: row;
Secara default flex-direction pada elemen yang menggunakan display: flex adalah row. Tidak perlu menggunakan `flex-direction: row`

2024-10-10 11:29 UTC, webprogramminghack commented on src/components/Dialog/Dialog.tsx
> +  // onConfirm,
onConfirm dan onClose harus diteruskan ke Button props

2024-10-10 14:22 UTC, RudyHarun99 reviewed
revisi 2, mohon koreksi dan arahannya, terima kasih

2024-11-05 08:46 UTC, webprogramminghack requested changes
Fix the code according to the comments provided

2024-11-05 08:46 UTC, webprogramminghack commented on src/components/Button/Button.module.scss
> +  align-items: center;
3 style berikut dapat dihapus saja, karena tidak memberikan styling apapun

2024-11-05 08:46 UTC, webprogramminghack commented on src/components/Button/Button.module.scss
> +  text-align: center;
Untuk style ini sebenernya tidak diperlukan karena secara default text sudah berada di tengah (center), yang disebabkan oleh padding

2024-11-05 08:46 UTC, webprogramminghack commented on src/components/Button/Button.module.scss
> +  height: rem-calc(45);
Untuk height saran saya gunakan padding saja, karena lebar ke samping sudah menggunakan padding

2024-11-07 11:59 UTC, RudyHarun99 commented on src/components/Button/Button.module.scss
> +  align-items: center;
done, 3 line tsb dihapus

2024-11-07 11:59 UTC, RudyHarun99 commented on src/components/Button/Button.module.scss
> +  text-align: center;
done, text-align dihapus

2024-11-07 12:00 UTC, RudyHarun99 commented on src/components/Button/Button.module.scss
> +  height: rem-calc(45);
done, height dihapus, gantinya padding atas dan bawah 13, kanan kiri 20

2025-01-09 07:52 UTC, webprogramminghack approved these changes
Assignment completed, good job

2025-01-09 07:52 UTC, closed without merging